name:                cosette
version:             0.1.0.0
synopsis:            Automated SQL prover
homepage:            cosette.cs.washington.edu
license:             MIT
license-file:        LICENSE.txt
author:              Shumo Chu
maintainer:          shumo.chu@gmail.com
category:            Database

extra-source-files:
- readme.md

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1 && <= 3.2
- HUnit >= 1.6 && <1.7
default-extensions:    OverloadedStrings

library:
  source-dirs: src

executables:
  hottsql-exe:
    main:                CoqCodeGen.lhs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cosette

tests:
  hottsql-test:
    main:                QueryParseTest.lhs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hcosette
